development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password: postgresql1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: postgresql1

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: postgres
  password: postgresql1
